# 工作流名称
name: Update Classified Shadowrocket Rules

# 触发条件
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 步骤1：检出你的仓库代码
      - name: Checkout repository
        # --- Git 问题修复：升级到 v4 并使用完整克隆 ---
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0 会获取所有历史记录，能更好地处理同步问题
          fetch-depth: 0

      # 步骤2：分类合并规则
      - name: Consolidate classified rules
        run: |
          set -e
          process_rules() {
            local type=$1
            local SOURCE_FILE="${type}_rule.txt"
            local OUTPUT_FILE="${type}_rule.list"
            if [ ! -f "$SOURCE_FILE" ]; then
              echo "Source file $SOURCE_FILE not found, skipping."
              return
            fi
            echo "--- Processing $SOURCE_FILE into $OUTPUT_FILE ---"
            echo "# ${type^} rules list for Shadowrocket" > $OUTPUT_FILE
            echo "# Generated on $(date -u)" >> $OUTPUT_FILE
            echo "" >> $OUTPUT_FILE
            while IFS= read -r url || [[ -n "$url" ]]; do
              if [[ -z "$url" || "$url" =~ ^# ]]; then
                continue
              fi
              echo "Fetching from $url"
              echo -e "\n# From: $url" >> $OUTPUT_FILE
              # 增加 User-Agent 对一些简单防护依然有效，我们保留它
              curl -sL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "$url" >> $OUTPUT_FILE
            done < "$SOURCE_FILE"
            echo "Successfully consolidated into $OUTPUT_FILE"
          }
          process_rules "reject"
          process_rules "direct"
          process_rules "proxy"

      # 步骤3：提交并推送到仓库
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add reject_rule.list direct_rule.list proxy_rule.list
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: Auto-update classified rules on $(date)"
            git pull --rebase
            git push
          fi
